In [1]:
import ghsl_time_consistent_cluster as tcc
import config as config

In [2]:
%load_ext autoreload
%autoreload 2

# 1. ETL Pipeline
Here we extract the data from the pop and smod rasters and copy it to postigs.

In [3]:
tcc.load_ghsl_rasters()

Running bash script with arguments:
CREATE EXTENSION
CREATE EXTENSION
Loading data for year 1975...
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 171
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 2
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
Loading complete for 1975
stderr: NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_raster" already exists, skipping
Processing 1/1: /Users/andrea/Desktop/PhD/Data/API/clusterdb/data/ghsl/pop/GHS_POP_E1975_GLOBE_R2023A_54009_1000_V1_0.tif
INFO: Using computed tile size: 256x256
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
Processing 1/1: /Users/andrea/Desktop/PhD/Data/API/clusterdb/data/ghsl/smod/GHS_SMOD_E1975_GLOBE_R2023A_54009_1000_V1_0.tif
INFO: Using computed tile size: 256x256
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
Return code: 0
Running bash script with arguments:
CREATE EXTENSION
CREATE EXTENSION
Loading data for year 1980...
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 171
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 2
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
Loading complete for 1980
stderr: NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_raster" already exists, skipping
Processing 1/1: /Users/andrea/Desktop/PhD/Data/API/clusterdb/data/ghsl/pop/GHS_POP_E1980_GLOBE_R2023A_54009_1000_V1_0.tif
INFO: Using computed tile size: 256x256
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
Processing 1/1: /Users/andrea/Desktop/PhD/Data/API/clusterdb/data/ghsl/smod/GHS_SMOD_E1980_GLOBE_R2023A_54009_1000_V1_0.tif
INFO: Using computed tile size: 256x256
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
Return code: 0
Running bash script with arguments:
CREATE EXTENSION
CREATE EXTENSION
Loading data for year 1985...
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 171
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 2
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
Loading complete for 1985
stderr: NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_raster" already exists, skipping
Processing 1/1: /Users/andrea/Desktop/PhD/Data/API/clusterdb/data/ghsl/pop/GHS_POP_E1985_GLOBE_R2023A_54009_1000_V1_0.tif
INFO: Using computed tile size: 256x256
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
Processing 1/1: /Users/andrea/Desktop/PhD/Data/API/clusterdb/data/ghsl/smod/GHS_SMOD_E1985_GLOBE_R2023A_54009_1000_V1_0.tif
INFO: Using computed tile size: 256x256
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
NOTICE:  Adding SRID constraint
NOTICE:  Adding scale-X constraint
NOTICE:  Adding scale-Y constraint
NOTICE:  Adding blocksize-X constraint
NOTICE:  Adding blocksize-Y constraint
NOTICE:  Adding alignment constraint
NOTICE:  Adding number of bands constraint
NOTICE:  Adding pixel type constraint
NOTICE:  Adding nodata value constraint
NOTICE:  Adding out-of-database constraint
NOTICE:  Adding maximum extent constraint
Return code: 0
Running bash script with arguments:
CREATE EXTENSION
CREATE EXTENSION
Loading data for year 1990...
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 171
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

addoverviewconstraints
------------------------
t
(1 row)

COMMIT
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 1000
COPY 2
COPY 1000
COPY 1000
COPY 556
COPY 648
COPY 162
COPY 45
addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addrasterconstraints
----------------------
t
(1 row)

addoverviewconstraints

# 2. Clusters
Here we build clusters, the central unit of analysis of this project. Clusters are defined build as follows:
- 2.0 Extract urban areas from the smod raster and then compute population zonal statistics over those urban areas using the pop raster

In [4]:
tcc.create_cluster()

2024-07-23 16:20:16,162 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2024-07-23 16:20:16,162 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-23 16:20:16,163 INFO sqlalchemy.engine.Engine select current_schema()
2024-07-23 16:20:16,163 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-23 16:20:16,164 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2024-07-23 16:20:16,164 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-23 16:20:16,165 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 16:20:16,168 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_1975";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_1975.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_1975;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_1975 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_1975
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 16:20:16,168 INFO sqlalchemy.engine.Engine [generated in 0.00021s] {}
2024-07-23 16:26:21,590 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 16:26:21,597 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 16:26:21,599 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_1980";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_1980.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_1980;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_1980 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_1980
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 16:26:21,599 INFO sqlalchemy.engine.Engine [generated in 0.00026s] {}
2024-07-23 16:32:56,199 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 16:32:56,205 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 16:32:56,206 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_1985";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_1985.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_1985;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_1985 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_1985
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 16:32:56,207 INFO sqlalchemy.engine.Engine [generated in 0.00025s] {}
2024-07-23 16:39:46,506 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 16:39:46,512 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 16:39:46,514 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_1990";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_1990.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_1990;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_1990 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_1990
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 16:39:46,514 INFO sqlalchemy.engine.Engine [generated in 0.00023s] {}
2024-07-23 16:47:06,488 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 16:47:06,496 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 16:47:06,498 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_1995";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_1995.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_1995;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_1995 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_1995
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 16:47:06,498 INFO sqlalchemy.engine.Engine [generated in 0.00021s] {}
2024-07-23 16:54:50,745 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 16:54:50,752 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 16:54:50,754 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_2000";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_2000.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_2000;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_2000 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_2000
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 16:54:50,754 INFO sqlalchemy.engine.Engine [generated in 0.00023s] {}
2024-07-23 17:02:49,978 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 17:02:49,986 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:02:49,987 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_2005";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_2005.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_2005;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_2005 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_2005
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 17:02:49,988 INFO sqlalchemy.engine.Engine [generated in 0.00029s] {}
2024-07-23 17:11:03,800 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 17:11:03,805 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:11:03,807 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_2010";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_2010.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_2010;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_2010 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_2010
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 17:11:03,807 INFO sqlalchemy.engine.Engine [generated in 0.00025s] {}
2024-07-23 17:19:36,733 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 17:19:36,739 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:19:36,741 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_2015";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_2015.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_2015;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_2015 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_2015
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 17:19:36,741 INFO sqlalchemy.engine.Engine [generated in 0.00023s] {}
2024-07-23 17:28:17,517 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 17:28:17,522 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:28:17,524 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "cluster_2020";

-- Create a binary raster from the smod raster with only urban and non-urban classes
CREATE TEMPORARY TABLE smod_binary ON COMMIT DROP AS
SELECT ST_Reclass(smod_2020.rast, 1,  '[0-21]:0, (21-30]:1', '1BB', nodataval := 0) AS rast
FROM smod_2020;

-- Create a temporary cluster geometry table with DBSCAN
CREATE TEMPORARY TABLE cluster_geom ON COMMIT DROP AS
WITH urban_pixels AS (
    SELECT (ST_PixelAsPolygons(rast, 1, TRUE)).*
    FROM smod_binary
),
dbscan AS (
    SELECT ST_ClusterDBSCAN(geom, eps := 1, minpoints := 1) OVER () AS cluster_id, geom
    FROM urban_pixels
)
SELECT cluster_id, ST_Union(geom) AS geom
FROM dbscan
GROUP BY cluster_id;

-- Create the cluster table with the geometry and population
CREATE TABLE cluster_2020 AS
WITH zonal_stats AS (
    SELECT cluster_id, (St_SummaryStats(St_Union(ST_Clip(rast, 1, geom, true)))).*
    FROM cluster_geom, pop_2020
    WHERE St_Intersects(rast,geom)
    GROUP BY cluster_id
)
SELECT cluster_id, sum AS population, geom
FROM zonal_stats JOIN cluster_geom USING(cluster_id);
2024-07-23 17:28:17,524 INFO sqlalchemy.engine.Engine [generated in 0.00025s] {}
2024-07-23 17:37:04,093 INFO sqlalchemy.engine.Engine COMMIT

# 3. Time consistent clusters
Here we build time consistent clusters i.e., clusters having a consistent id across time. We do this by:

- 3.1 Create a table with all clusters in all years. Create the "cluster intersection matching": a matching where two clusters (from different years) are matched if they intersect.
- 3.2 Create a crosswalk table between cluster ids and time consistent cluster ids. Time consistent clusters are defined as connected components of bipartite graph representing the cluster intersection matching. 
- 3.3 Create a table with time consistent clusters geometry. Create a table with the time consistent cluster population across years.

In [5]:
tcc.create_multiyear_tables_and_cluster_intersection_matching()

2024-07-23 17:37:04,228 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:37:04,229 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS multiyear_cluster
2024-07-23 17:37:04,229 INFO sqlalchemy.engine.Engine [generated in 0.00025s] {}
2024-07-23 17:37:04,230 INFO sqlalchemy.engine.Engine CREATE TABLE multiyear_cluster AS (SELECT 1975 as year, cluster_id, population, geom FROM cluster_1975 UNION ALL SELECT 1980 as year, cluster_id, population, geom FROM cluster_1980 UNION ALL SELECT 1985 as year, cluster_id, population, geom FROM cluster_1985 UNION ALL SELECT 1990 as year, cluster_id, population, geom FROM cluster_1990 UNION ALL SELECT 1995 as year, cluster_id, population, geom FROM cluster_1995 UNION ALL SELECT 2000 as year, cluster_id, population, geom FROM cluster_2000 UNION ALL SELECT 2005 as year, cluster_id, population, geom FROM cluster_2005 UNION ALL SELECT 2010 as year, cluster_id, population, geom FROM cluster_2010 UNION ALL SELECT 2015 as year, cluster_id, population, geom FROM cluster_2015 UNION ALL SELECT 2020 as year, cluster_id, population, geom FROM cluster_2020 )
2024-07-23 17:37:04,230 INFO sqlalchemy.engine.Engine [generated in 0.00020s] {}
2024-07-23 17:37:04,886 INFO sqlalchemy.engine.Engine CREATE INDEX ON multiyear_cluster USING GIST (geom)
2024-07-23 17:37:04,887 INFO sqlalchemy.engine.Engine [generated in 0.00143s] {}
2024-07-23 17:37:05,602 INFO sqlalchemy.engine.Engine COMMIT
2024-07-23 17:37:05,607 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:37:05,607 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS cluster_intersection_matching
2024-07-23 17:37:05,607 INFO sqlalchemy.engine.Engine [generated in 0.00024s] {}
2024-07-23 17:37:05,608 INFO sqlalchemy.engine.Engine
        CREATE TABLE cluster_intersection_matching AS
        SELECT c1.year as y1, c1.cluster_id AS id1, c2.year AS y2, c2.cluster_id AS id2
        FROM multiyear_cluster c1 JOIN multiyear_cluster c2
        ON ST_Intersects(c1.geom, c2.geom);

2024-07-23 17:37:05,608 INFO sqlalchemy.engine.Engine [generated in 0.00021s] {}
2024-07-23 17:37:41,908 INFO sqlalchemy.engine.Engine COMMIT

In [6]:
tcc.create_crosswalk_cluster_uid_to_cluster_id()

2024-07-23 17:37:41,934 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:37:41,935 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-07-23 17:37:41,935 INFO sqlalchemy.engine.Engine [generated in 0.00075s] {'table_name': 'SELECT * FROM cluster_intersection_matching', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2024-07-23 17:37:41,937 INFO sqlalchemy.engine.Engine SELECT * FROM cluster_intersection_matching
2024-07-23 17:37:41,937 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-07-23 17:37:53,309 INFO sqlalchemy.engine.Engine ROLLBACK
2024-07-23 17:39:48,420 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 17:39:48,421 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-07-23 17:39:48,421 INFO sqlalchemy.engine.Engine [cached since 126.5s ago] {'table_name': 'crosswalk_cluster_uid_to_cluster_id', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2024-07-23 17:39:48,423 INFO sqlalchemy.engine.Engine
CREATE TABLE crosswalk_cluster_uid_to_cluster_id (
	cluster_uid BIGINT,
	year BIGINT,
	cluster_id BIGINT
)


2024-07-23 17:39:48,424 INFO sqlalchemy.engine.Engine [no key 0.00020s] {}
2024-07-23 17:39:50,284 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)
2024-07-23 17:39:50,285 INFO sqlalchemy.engine.Engine [generated in 1.61599s (insertmanyvalues) 1/967 (unordered)] {'cluster_uid__0': 0, 'year__0': 1985, 'cluster_id__0': 653, 'cluster_uid__1': 0, 'year__1': 2010, 'cluster_id__1': 669, 'cluster_uid__2': 0, 'year__2': 2005, 'cluster_id__2': 669, 'cluster_uid__3': 0, 'year__3': 1990, 'cluster_id__3': 662, 'cluster_uid__4': 0, 'year__4': 2015, 'cluster_id__4': 663, 'cluster_uid__5': 0, 'year__5': 2020, 'cluster_id__5': 655, 'cluster_uid__6': 0, 'year__6': 1995, 'cluster_id__6': 673, 'cluster_uid__7': 0, 'year__7': 1980, 'cluster_id__7': 649, 'cluster_uid__8': 0, 'year__8': 1975, 'cluster_id__8': 652, 'cluster_uid__9': 0, 'year__9': 2000, 'cluster_id__9': 673, 'cluster_uid__10': 1, 'year__10': 1975, 'cluster_id__10': 273, 'cluster_uid__11': 1, 'year__11': 1985, 'cluster_id__11': 269, 'cluster_uid__12': 1, 'year__12': 2015, 'cluster_id__12': 270, 'cluster_uid__13': 1, 'year__13': 2020, 'cluster_id__13': 266, 'cluster_uid__14': 1, 'year__14': 2010, 'cluster_id__14': 273, 'cluster_uid__15': 1, 'year__15': 1990, 'cluster_id__15': 270, 'cluster_uid__16': 1, 'year__16': 2000 ... 2900 parameters truncated ... 'year__983': 2015, 'cluster_id__983': 771, 'cluster_uid__984': 96, 'year__984': 2000, 'cluster_id__984': 778, 'cluster_uid__985': 97, 'year__985': 1995, 'cluster_id__985': 229, 'cluster_uid__986': 97, 'year__986': 2020, 'cluster_id__986': 217, 'cluster_uid__987': 97, 'year__987': 2000, 'cluster_id__987': 224, 'cluster_uid__988': 97, 'year__988': 2005, 'cluster_id__988': 222, 'cluster_uid__989': 97, 'year__989': 2015, 'cluster_id__989': 219, 'cluster_uid__990': 97, 'year__990': 1985, 'cluster_id__990': 221, 'cluster_uid__991': 97, 'year__991': 1990, 'cluster_id__991': 222, 'cluster_uid__992': 97, 'year__992': 2010, 'cluster_id__992': 221, 'cluster_uid__993': 97, 'year__993': 1980, 'cluster_id__993': 219, 'cluster_uid__994': 97, 'year__994': 1975, 'cluster_id__994': 222, 'cluster_uid__995': 98, 'year__995': 2015, 'cluster_id__995': 1035, 'cluster_uid__996': 98, 'year__996': 2000, 'cluster_id__996': 1052, 'cluster_uid__997': 98, 'year__997': 1990, 'cluster_id__997': 1036, 'cluster_uid__998': 98, 'year__998': 1995, 'cluster_id__998': 1055, 'cluster_uid__999': 98, 'year__999': 2005, 'cluster_id__999': 1047}
2024-07-23 17:39:50,305 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)
2024-07-23 17:39:50,305 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/967 (unordered)] {'cluster_uid__0': 98, 'year__0': 1975, 'cluster_id__0': 1006, 'cluster_uid__1': 98, 'year__1': 2020, 'cluster_id__1': 1025, 'cluster_uid__2': 98, 'year__2': 1980, 'cluster_id__2': 1010, 'cluster_uid__3': 98, 'year__3': 2010, 'cluster_id__3': 1041, 'cluster_uid__4': 98, 'year__4': 1985, 'cluster_id__4': 1022, 'cluster_uid__5': 99, 'year__5': 1995, 'cluster_id__5': 1057, 'cluster_uid__6': 99, 'year__6': 2015, 'cluster_id__6': 1037, 'cluster_uid__7': 99, 'year__7': 2005, 'cluster_id__7': 1049, 'cluster_uid__8': 99, 'year__8': 1985, 'cluster_id__8': 1024, 'cluster_uid__9': 99, 'year__9': 1990, 'cluster_id__9': 1038, 'cluster_uid__10': 99, 'year__10': 2010, 'cluster_id__10': 1043, 'cluster_uid__11': 99, 'year__11': 2000, 'cluster_id__11': 1054, 'cluster_uid__12': 99, 'year__12': 1975, 'cluster_id__12': 1008, 'cluster_uid__13': 99, 'year__13': 2020, 'cluster_id__13': 1027, 'cluster_uid__14': 99, 'year__14': 1980, 'cluster_id__14': 1012, 'cluster_uid__15': 100, 'year__15': 1990, 'cluster_id__15': 794, 'cluster_uid__16': 100, 'year__16': 2005 ... 2900 parameters truncated ... 'year__983': 1995, 'cluster_id__983': 33, 'cluster_uid__984': 192, 'year__984': 2000, 'cluster_id__984': 33, 'cluster_uid__985': 193, 'year__985': 1980, 'cluster_id__985': 951, 'cluster_uid__986': 193, 'year__986': 1975, 'cluster_id__986': 947, 'cluster_uid__987': 193, 'year__987': 1985, 'cluster_id__987': 963, 'cluster_uid__988': 193, 'year__988': 2000, 'cluster_id__988': 997, 'cluster_uid__989': 193, 'year__989': 2015, 'cluster_id__989': 986, 'cluster_uid__990': 193, 'year__990': 2020, 'cluster_id__990': 982, 'cluster_uid__991': 193, 'year__991': 2005, 'cluster_id__991': 995, 'cluster_uid__992': 193, 'year__992': 2010, 'cluster_id__992': 992, 'cluster_uid__993': 193, 'year__993': 1990, 'cluster_id__993': 976, 'cluster_uid__994': 193, 'year__994': 1995, 'cluster_id__994': 996, 'cluster_uid__995': 194, 'year__995': 1995, 'cluster_id__995': 1028, 'cluster_uid__996': 194, 'year__996': 2000, 'cluster_id__996': 1026, 'cluster_uid__997': 194, 'year__997': 1990, 'cluster_id__997': 1006, 'cluster_uid__998': 194, 'year__998': 1985, 'cluster_id__998': 994, 'cluster_uid__999': 194, 'year__999': 1980, 'cluster_id__999': 982}
2024-07-23 17:39:50,314 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)
2024-07-23 17:39:50,315 INFO sqlalchemy.engine.Engine [insertmanyvalues 3/967 (unordered)] {'cluster_uid__0': 194, 'year__0': 1975, 'cluster_id__0': 978, 'cluster_uid__1': 195, 'year__1': 2015, 'cluster_id__1': 1009, 'cluster_uid__2': 195, 'year__2': 1975, 'cluster_id__2': 972, 'cluster_uid__3': 195, 'year__3': 1990, 'cluster_id__3': 1001, 'cluster_uid__4': 195, 'year__4': 1980, 'cluster_id__4': 976, 'cluster_uid__5': 195, 'year__5': 2000, 'cluster_id__5': 1021, 'cluster_uid__6': 195, 'year__6': 2020, 'cluster_id__6': 1000, 'cluster_uid__7': 195, 'year__7': 1985, 'cluster_id__7': 988, 'cluster_uid__8': 195, 'year__8': 1995, 'cluster_id__8': 1022, 'cluster_uid__9': 195, 'year__9': 2010, 'cluster_id__9': 1015, 'cluster_uid__10': 195, 'year__10': 2005, 'cluster_id__10': 1020, 'cluster_uid__11': 196, 'year__11': 1990, 'cluster_id__11': 778, 'cluster_uid__12': 196, 'year__12': 1975, 'cluster_id__12': 761, 'cluster_uid__13': 196, 'year__13': 1985, 'cluster_id__13': 767, 'cluster_uid__14': 196, 'year__14': 1995, 'cluster_id__14': 791, 'cluster_uid__15': 196, 'year__15': 2005, 'cluster_id__15': 790, 'cluster_uid__16': 196, 'year__16': 2000 ... 2900 parameters truncated ... 'year__983': 2010, 'cluster_id__983': 884, 'cluster_uid__984': 294, 'year__984': 2015, 'cluster_id__984': 878, 'cluster_uid__985': 294, 'year__985': 2005, 'cluster_id__985': 885, 'cluster_uid__986': 294, 'year__986': 1995, 'cluster_id__986': 883, 'cluster_uid__987': 294, 'year__987': 2020, 'cluster_id__987': 874, 'cluster_uid__988': 294, 'year__988': 2000, 'cluster_id__988': 886, 'cluster_uid__989': 294, 'year__989': 1990, 'cluster_id__989': 865, 'cluster_uid__990': 295, 'year__990': 2010, 'cluster_id__990': 739, 'cluster_uid__991': 295, 'year__991': 1980, 'cluster_id__991': 705, 'cluster_uid__992': 295, 'year__992': 1995, 'cluster_id__992': 738, 'cluster_uid__993': 295, 'year__993': 1985, 'cluster_id__993': 714, 'cluster_uid__994': 295, 'year__994': 1990, 'cluster_id__994': 725, 'cluster_uid__995': 295, 'year__995': 2020, 'cluster_id__995': 727, 'cluster_uid__996': 295, 'year__996': 2005, 'cluster_id__996': 738, 'cluster_uid__997': 295, 'year__997': 2015, 'cluster_id__997': 733, 'cluster_uid__998': 295, 'year__998': 1975, 'cluster_id__998': 710, 'cluster_uid__999': 295, 'year__999': 2000, 'cluster_id__999': 739}
2024-07-23 17:39:50,324 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)
2024-07-23 17:39:50,325 INFO sqlalchemy.engine.Engine [insertmanyvalues 4/967 (unordered)] {'cluster_uid__0': 296, 'year__0': 2010, 'cluster_id__0': 43, 'cluster_uid__1': 296, 'year__1': 1980, 'cluster_id__1': 47, 'cluster_uid__2': 296, 'year__2': 1975, 'cluster_id__2': 48, 'cluster_uid__3': 296, 'year__3': 2000, 'cluster_id__3': 47, 'cluster_uid__4': 296, 'year__4': 1995, 'cluster_id__4': 48, 'cluster_uid__5': 296, 'year__5': 2020, 'cluster_id__5': 44, 'cluster_uid__6': 296, 'year__6': 1990, 'cluster_id__6': 48, 'cluster_uid__7': 296, 'year__7': 2015, 'cluster_id__7': 43, 'cluster_uid__8': 296, 'year__8': 1985, 'cluster_id__8': 48, 'cluster_uid__9': 296, 'year__9': 2005, 'cluster_id__9': 45, 'cluster_uid__10': 297, 'year__10': 1975, 'cluster_id__10': 298, 'cluster_uid__11': 297, 'year__11': 1995, 'cluster_id__11': 307, 'cluster_uid__12': 297, 'year__12': 2010, 'cluster_id__12': 306, 'cluster_uid__13': 297, 'year__13': 2005, 'cluster_id__13': 306, 'cluster_uid__14': 297, 'year__14': 2015, 'cluster_id__14': 303, 'cluster_uid__15': 297, 'year__15': 1990, 'cluster_id__15': 298, 'cluster_uid__16': 297, 'year__16': 1985 ... 2900 parameters truncated ... 'year__983': 1985, 'cluster_id__983': 628, 'cluster_uid__984': 395, 'year__984': 1980, 'cluster_id__984': 624, 'cluster_uid__985': 395, 'year__985': 1990, 'cluster_id__985': 636, 'cluster_uid__986': 396, 'year__986': 2015, 'cluster_id__986': 104, 'cluster_uid__987': 396, 'year__987': 1980, 'cluster_id__987': 116, 'cluster_uid__988': 396, 'year__988': 2000, 'cluster_id__988': 113, 'cluster_uid__989': 396, 'year__989': 2005, 'cluster_id__989': 110, 'cluster_uid__990': 396, 'year__990': 2010, 'cluster_id__990': 104, 'cluster_uid__991': 396, 'year__991': 1975, 'cluster_id__991': 119, 'cluster_uid__992': 396, 'year__992': 1985, 'cluster_id__992': 116, 'cluster_uid__993': 396, 'year__993': 1995, 'cluster_id__993': 117, 'cluster_uid__994': 396, 'year__994': 2020, 'cluster_id__994': 104, 'cluster_uid__995': 396, 'year__995': 1990, 'cluster_id__995': 116, 'cluster_uid__996': 397, 'year__996': 1990, 'cluster_id__996': 308, 'cluster_uid__997': 397, 'year__997': 2010, 'cluster_id__997': 316, 'cluster_uid__998': 397, 'year__998': 1995, 'cluster_id__998': 317, 'cluster_uid__999': 397, 'year__999': 2005, 'cluster_id__999': 315}
2024-07-23 17:39:50,337 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)
2024-07-23 17:39:50,337 INFO sqlalchemy.engine.Engine [insertmanyvalues 5/967 (unordered)] {'cluster_uid__0': 397, 'year__0': 2000, 'cluster_id__0': 316, 'cluster_uid__1': 397, 'year__1': 1985, 'cluster_id__1': 306, 'cluster_uid__2': 397, 'year__2': 1975, 'cluster_id__2': 306, 'cluster_uid__3': 397, 'year__3': 2020, 'cluster_id__3': 310, 'cluster_uid__4': 397, 'year__4': 1980, 'cluster_id__4': 303, 'cluster_uid__5': 397, 'year__5': 2015, 'cluster_id__5': 315, 'cluster_uid__6': 398, 'year__6': 2000, 'cluster_id__6': 285, 'cluster_uid__7': 398, 'year__7': 1975, 'cluster_id__7': 286, 'cluster_uid__8': 398, 'year__8': 2005, 'cluster_id__8': 284, 'cluster_uid__9': 398, 'year__9': 1985, 'cluster_id__9': 283, 'cluster_uid__10': 398, 'year__10': 1995, 'cluster_id__10': 290, 'cluster_uid__11': 398, 'year__11': 2010, 'cluster_id__11': 284, 'cluster_uid__12': 398, 'year__12': 1980, 'cluster_id__12': 282, 'cluster_uid__13': 398, 'year__13': 2020, 'cluster_id__13': 277, 'cluster_uid__14': 398, 'year__14': 1990, 'cluster_id__14': 284, 'cluster_uid__15': 398, 'year__15': 2015, 'cluster_id__15': 281, 'cluster_uid__16': 399, 'year__16': 1980 ... 2900 parameters truncated ... 'year__983': 1980, 'cluster_id__983': 921, 'cluster_uid__984': 499, 'year__984': 1995, 'cluster_id__984': 966, 'cluster_uid__985': 499, 'year__985': 1990, 'cluster_id__985': 944, 'cluster_uid__986': 499, 'year__986': 2010, 'cluster_id__986': 964, 'cluster_uid__987': 500, 'year__987': 1975, 'cluster_id__987': 156, 'cluster_uid__988': 500, 'year__988': 1980, 'cluster_id__988': 153, 'cluster_uid__989': 500, 'year__989': 1985, 'cluster_id__989': 155, 'cluster_uid__990': 500, 'year__990': 1995, 'cluster_id__990': 162, 'cluster_uid__991': 500, 'year__991': 2000, 'cluster_id__991': 157, 'cluster_uid__992': 500, 'year__992': 2020, 'cluster_id__992': 154, 'cluster_uid__993': 500, 'year__993': 2015, 'cluster_id__993': 154, 'cluster_uid__994': 500, 'year__994': 2010, 'cluster_id__994': 154, 'cluster_uid__995': 500, 'year__995': 2005, 'cluster_id__995': 155, 'cluster_uid__996': 500, 'year__996': 1990, 'cluster_id__996': 157, 'cluster_uid__997': 501, 'year__997': 1985, 'cluster_id__997': 947, 'cluster_uid__998': 501, 'year__998': 1980, 'cluster_id__998': 936, 'cluster_uid__999': 501, 'year__999': 1975, 'cluster_id__999': 932}
2024-07-23 17:39:50,347 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)
2024-07-23 17:39:50,347 INFO sqlalchemy.engine.Engine [insertmanyvalues 6/967 (unordered)] {'cluster_uid__0': 501, 'year__0': 2005, 'cluster_id__0': 979, 'cluster_uid__1': 501, 'year__1': 2000, 'cluster_id__1': 981, 'cluster_uid__2': 501, 'year__2': 1990, 'cluster_id__2': 960, 'cluster_uid__3': 501, 'year__3': 2010, 'cluster_id__3': 976, 'cluster_uid__4': 501, 'year__4': 2015, 'cluster_id__4': 970, 'cluster_uid__5': 501, 'year__5': 2020, 'cluster_id__5': 968, 'cluster_uid__6': 501, 'year__6': 1995, 'cluster_id__6': 980, 'cluster_uid__7': 502, 'year__7': 2020, 'cluster_id__7': 642, 'cluster_uid__8': 502, 'year__8': 2010, 'cluster_id__8': 656, 'cluster_uid__9': 502, 'year__9': 1985, 'cluster_id__9': 642, 'cluster_uid__10': 502, 'year__10': 1975, 'cluster_id__10': 641, 'cluster_uid__11': 502, 'year__11': 1990, 'cluster_id__11': 650, 'cluster_uid__12': 502, 'year__12': 2005, 'cluster_id__12': 657, 'cluster_uid__13': 502, 'year__13': 2015, 'cluster_id__13': 650, 'cluster_uid__14': 502, 'year__14': 1995, 'cluster_id__14': 661, 'cluster_uid__15': 502, 'year__15': 1980, 'cluster_id__15': 638, 'cluster_uid__16': 502, 'year__16': 2000 ... 2900 parameters truncated ... 'year__983': 2010, 'cluster_id__983': 790, 'cluster_uid__984': 603, 'year__984': 2015, 'cluster_id__984': 784, 'cluster_uid__985': 603, 'year__985': 1995, 'cluster_id__985': 792, 'cluster_uid__986': 603, 'year__986': 2000, 'cluster_id__986': 793, 'cluster_uid__987': 603, 'year__987': 1975, 'cluster_id__987': 762, 'cluster_uid__988': 603, 'year__988': 1980, 'cluster_id__988': 758, 'cluster_uid__989': 604, 'year__989': 2010, 'cluster_id__989': 741, 'cluster_uid__990': 604, 'year__990': 1980, 'cluster_id__990': 707, 'cluster_uid__991': 604, 'year__991': 1985, 'cluster_id__991': 716, 'cluster_uid__992': 604, 'year__992': 1975, 'cluster_id__992': 712, 'cluster_uid__993': 604, 'year__993': 1990, 'cluster_id__993': 727, 'cluster_uid__994': 604, 'year__994': 2000, 'cluster_id__994': 741, 'cluster_uid__995': 604, 'year__995': 1995, 'cluster_id__995': 740, 'cluster_uid__996': 604, 'year__996': 2020, 'cluster_id__996': 729, 'cluster_uid__997': 604, 'year__997': 2015, 'cluster_id__997': 735, 'cluster_uid__998': 604, 'year__998': 2005, 'cluster_id__998': 740, 'cluster_uid__999': 605, 'year__999': 1990, 'cluster_id__999': 192}
2024-07-23 17:39:50,356 INFO sqlalchemy.engine.Engine INSERT INTO crosswalk_cluster_uid_to_cluster_id (cluster_uid, year, cluster_id) VALUES (%(cluster_uid__0)s, %(year__0)s, %(cluster_id__0)s), (%(cluster_uid__1)s, %(year__1)s, %(cluster_id__1)s), (%(cluster_uid__2)s, %(year__2)s, %(cluster_id__2)s), ( ... 59405 characters truncated ... 8)s, %(year__998)s, %(cluster_id__998)s), (%(cluster_uid__999)s, %(year__999)s, %(cluster_id__999)s)

In [13]:
tcc.create_time_consistent_cluster_pre_geocoding()

2024-07-23 23:14:46,333 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 23:14:46,334 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS "time_consistent_cluster_pre_geocoding";
DROP TABLE IF EXISTS "time_consistent_cluster_geometry_pre_geocoding";

-- Create the time consistent cluster geometry table
CREATE TABLE "time_consistent_cluster_geometry_pre_geocoding" AS
WITH multiyear_cluster_with_uid AS (
    SELECT m.cluster_uid, c.year, c.cluster_id, geom
    FROM "crosswalk_cluster_uid_to_cluster_id" m JOIN "multiyear_cluster" c
    ON m.cluster_id = c.cluster_id AND m.year = c.year
)
SELECT cluster_uid, ST_Union(geom) AS geom
FROM multiyear_cluster_with_uid
GROUP BY cluster_uid;

CREATE INDEX ON "time_consistent_cluster_geometry_pre_geocoding" USING GIST (geom);

-- Create the time consistent cluster table
CREATE TABLE "time_consistent_cluster_pre_geocoding" AS
WITH multiyear_cluster_with_uid AS (
    SELECT m.cluster_uid, c.year, c.cluster_id, population
    FROM "crosswalk_cluster_uid_to_cluster_id" m JOIN "multiyear_cluster" c
    ON m.cluster_id = c.cluster_id AND m.year = c.year
)
SELECT cluster_uid, year, SUM(population) AS population
FROM multiyear_cluster_with_uid
GROUP BY cluster_uid, year;
2024-07-23 23:14:46,335 INFO sqlalchemy.engine.Engine [generated in 0.00029s] {}
2024-07-23 23:15:34,480 INFO sqlalchemy.engine.Engine COMMIT

# 4. Country Geocoding
Here we load the country boarder data and assign to each cluster, year pair the country that the cluster belongs into the given year. 
- 4.1 Load the country boarder data
- 4.2 Assign the country to each cluster, year pair. Here we make a couple of choices thar are worth noting:
    - Border clusters are assigned to the country with the largest area of intersection
    - Small islands that intersect no country are removed. These are typically islands so small that they are not counted in the country border dataset.

In [14]:
tcc.load_country_borders()

2024-07-23 23:15:46,253 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 23:15:46,254 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS country_borders
2024-07-23 23:15:46,254 INFO sqlalchemy.engine.Engine [cached since 950.1s ago] {}
2024-07-23 23:15:46,257 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS crosswalk_cshape_to_world_bank_codes
2024-07-23 23:15:46,257 INFO sqlalchemy.engine.Engine [cached since 950.1s ago] {}
2024-07-23 23:15:46,259 INFO sqlalchemy.engine.Engine COMMIT
Running bash script with arguments:
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
ALTER TABLE
CREATE TABLE
COPY 185
Data loaded successfully.
Return code: 0

In [19]:
tcc.geocode_cluster_with_country()

2024-07-23 23:20:32,480 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-23 23:20:32,483 INFO sqlalchemy.engine.Engine DROP TABLE IF EXISTS time_consistent_cluster;
DROP TABLE IF EXISTS time_consistent_cluster_geometry;

-- Temporary table of transformed country borders
CREATE TEMPORARY TABLE temp_country_geom_transformed ON COMMIT DROP AS
SELECT gwcode, gwsyear, gweyear, ST_transform(the_geom, 54009) AS geom
FROM country_borders;

CREATE INDEX ON temp_country_geom_transformed USING GIST (geom);

-- Temporary table of cluster-country matching
CREATE TEMPORARY TABLE temp_cluster_country_matching ON COMMIT DROP AS
SELECT cluster_uid, year, gwcode, gwsyear, gweyear
FROM (time_consistent_cluster_pre_geocoding JOIN time_consistent_cluster_geometry_pre_geocoding USING (cluster_uid)) cluster
JOIN temp_country_geom_transformed country ON st_intersects(cluster.geom, country.geom)
WHERE (gwsyear < year AND year <= gweyear) OR (year = 2020 AND gweyear = 2019);

-- Temporary table of clusters that match with multiple countries (i.e., border clusters)
CREATE TEMPORARY TABLE temp_cluster_country_matching_multiple_countries ON COMMIT DROP AS
WITH countries_matched_per_cluster AS (
    SELECT cluster_uid, year, COUNT(*) AS n_matched_countries
    FROM temp_cluster_country_matching
    GROUP BY cluster_uid, year
),
clusters_matched_with_multiple_countries AS (
  SELECT cluster_uid, year, gwcode, gwsyear, gweyear
  FROM temp_cluster_country_matching JOIN (SELECT * FROM countries_matched_per_cluster WHERE n_matched_countries >= 2) USING (cluster_uid, year)
),
cluster_country_intersection_areas AS (
    SELECT cluster_uid, year, gwcode, ST_Area(ST_Intersection(cluster.geom, country.geom)) AS intersection_area
    FROM clusters_matched_with_multiple_countries JOIN time_consistent_cluster_geometry_pre_geocoding cluster USING(cluster_uid)
    JOIN temp_country_geom_transformed country USING (gwcode, gwsyear, gweyear)
),
cluster_country_intersection_areas_ranked AS (
    SELECT cluster_uid, year, gwcode, RANK() OVER(PARTITION BY cluster_uid, year ORDER BY intersection_area DESC) AS area_rank
    FROM cluster_country_intersection_areas
)
SELECT cluster_uid, year, gwcode
FROM cluster_country_intersection_areas_ranked WHERE area_rank = 1;

-- Temporary table of clusters that match with a single country (i.e., interior clusters)
CREATE TEMPORARY TABLE temp_cluster_country_matching_single_countries ON COMMIT DROP AS
WITH countries_matched_per_cluster AS (
    SELECT cluster_uid, year, COUNT(*) AS n_matched_countries
    FROM temp_cluster_country_matching
    GROUP BY cluster_uid, year
)
SELECT cluster_uid, year, gwcode
FROM temp_cluster_country_matching JOIN countries_matched_per_cluster USING (cluster_uid, year)
WHERE n_matched_countries = 1;

-- Final table of cluster-country matching where we cleaned clustered matching with multiple countries
-- and added world bank codes
CREATE TEMPORARY TABLE temp_cluster_country_matching_clean ON COMMIT DROP AS
WITH cluster_country_matching AS (
    SELECT * FROM temp_cluster_country_matching_single_countries
    UNION ALL
    SELECT * FROM temp_cluster_country_matching_multiple_countries)
SELECT cluster_uid, year, gwcode AS cshape_code, world_bank_code
FROM cluster_country_matching JOIN crosswalk_cshape_to_world_bank_codes
ON gwcode = cshape_code;

-- We add country information to the time consistent cluster table
-- Note: by doing this we drop clusters that are matched to no country
-- These are usually small clusters on islands off the coast of a country which are too small to be counted in the country border dataset.
CREATE TABLE time_consistent_cluster AS
SELECT cluster_uid, year, population, cshape_code, world_bank_code
FROM time_consistent_cluster_pre_geocoding JOIN temp_cluster_country_matching_clean USING (cluster_uid, year);

-- We filter the time consistent cluster geometry table to only include clusters that have country information
CREATE TABLE time_consistent_cluster_geometry AS
SELECT cluster_uid, geom
FROM time_consistent_cluster_geometry_pre_geocoding
WHERE cluster_uid IN (SELECT DISTINCT cluster_uid FROM time_consistent_cluster);

ALTER TABLE "time_consistent_cluster_geometry" ADD PRIMARY KEY (cluster_uid);
CREATE INDEX ON "time_consistent_cluster_geometry" USING GIST (geom);

ALTER TABLE "time_consistent_cluster" ADD PRIMARY KEY (cluster_uid, year);
ALTER TABLE "time_consistent_cluster" ADD FOREIGN KEY (cluster_uid) REFERENCES "time_consistent_cluster_geometry"(cluster_uid);



2024-07-23 23:20:32,484 INFO sqlalchemy.engine.Engine [generated in 0.00044s] {}
2024-07-23 23:20:45,163 INFO sqlalchemy.engine.Engine COMMIT